PIN-4414 BKE - catalog-process: missing descriptor archiving
pagopa/interop-be-catalog-process pull request #223
Opened 2024-01-17 12:37 UTC by nttdata-rtorsoli

2024-01-22 11:45 UTC, beetlecrunch commented on src/main/scala/it/pagopa/interop/catalogprocess/api/impl/ProcessApiServiceImpl.scala
> +  private[this] def deprecateOrArchiveDescriptorOrCancelPublication(
May I suggest renaming this function or splitting it into smaller ones?

2024-01-23 13:19 UTC, galales requested changes

2024-01-23 13:19 UTC, galales commented on src/test/scala/it/pagopa/interop/catalogprocess/CatalogProcessSpec.scala
> +// "Descriptor suspension" should {
tests still commented

2024-01-23 16:54 UTC, beetlecrunch approved these changes

2024-01-25 13:13 UTC, galales approved these changes

2024-01-29 17:46 UTC, merged